/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: (typeof import('ant-design-vue/es'))['Col']
    AForm: (typeof import('ant-design-vue/es'))['Form']
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARow: (typeof import('ant-design-vue/es'))['Row']
    ASwitch: (typeof import('ant-design-vue/es'))['Switch']
    ATypographyText: (typeof import('ant-design-vue/es'))['TypographyText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
